# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1a28349fe7659977acfb7bd2dc4daf77"
name = "DEV HoangDH mini app"
application_url = "https://untenuous-li-frothily.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products, read_themes, read_customers, write_themes"

[auth]
redirect_urls = [ "https://untenuous-li-frothily.ngrok-free.dev/api/auth" ]
